version: '3.3'

services:
    frontend: 
        container_name: corona-map
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/Dockerfile 
        ports:
            - ${FRONTEND_CONTAINER_PORT}:80
        env_file: .env
#     cors:
#         image: redocly/cors-anywhere
#         env_file: .env

# networks:
#     cors-network:
#         driver: bridge