apiVersion: v1
kind: Pod
metadata:
  name: corona-web-app
  labels:
    purpose: web-app
spec:
  containers:
    - name: corona-web-app
      image: de.icr.io/muni_coronamap/web-api@sha256:256b62a57e89da25107cb7c254780031b8e8ab02454221a0720758fb04696c78
      env:
        - name: REACT_APP_BASE_URL
          value: http://169.51.203.137:32295/https://data.korona.gov.sk/api
