apiVersion: v1
kind: Pod
metadata:
  name: corona-web-app
  labels:
    purpose: web-app
spec:
  containers:
    - name: corona-web-app
      image: de.icr.io/muni_coronamap/muni_coronamap@sha256:48be692495ebf139b27a5b32ab337d251391bd13822c43079c67875238d45332
      env:
        - name: REACT_APP_BASE_URL
          value: http://169.51.203.137:32324/https://data.korona.gov.sk/api
