apiVersion: v1
kind: Pod
metadata:
  name: corona-cors-app
  labels:
    purpose: corona
spec:
  containers:
    - name: corona-cors-app
      image: de.icr.io/muni_coronamap/cors_service@sha256:f70cba287d76a1031ee8aa453f9fdb83e7bf65aff7c226960b1886a060e80def
