# The first stage
# Build React static files
FROM node:13.12.0-alpine as build

WORKDIR /app/frontend
COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm ci --silent
COPY ./frontend/ ./
RUN npm run-script build

# The second stage
# Copy React static files and start nginx
FROM nginx:stable-alpine
COPY ./docker/config /etc/nginx/conf.d
COPY --from=build /app/frontend/build /usr/share/nginx/html
RUN chmod +x /etc/nginx/conf.d/entrypoint.sh
CMD ["/etc/nginx/conf.d/entrypoint.sh"]